;;; ventura-xcode-default-theme.el - Ventura Default Xcode Theme ported from VSCode.

;;; Code:

(deftheme ventura-xcode-default)

(defcustom ventura-xcode-default-box-org-todo t
  "Set box around TODO items in org-mode"
  :type 'boolean
  :group 'dark-plus)

(defcustom ventura-xcode-default-scale-org-faces t
  "Scale headlines and other org faces"
  :type 'boolean
  :group 'dark-plus)

(defcustom ventura-xcode-default-invert-hl-todo t
  "Set (:invert-video t) on hl-todo face"
  :type 'boolean
  :group 'dark-plus)

(let* ((class '((class color) (min-colors 89)))
      (aqua-pearl            "#7ac8b6")
      (black                 "#000000")
      (black-charcoal        "#2f2e30")
      (black-chinese         "#101010")
      (black-olive           "#403e3e")
      (black-pine-tree       "#2c2c2b")
      (black-raisin          "#232222")
      (blue-cornflower       "#6796e6")
      (blue-dodger           "#128cff")
      (blue-jeans            "#53a5fb")
      (blue-queen            "#3675a2")
      (gold-satin-sheen      "#cd9731")
      (golden-poppy          "#ffc501")
      (gray-davy             "#555555")
      (gray-jet              "#353333")
      (gray-metal            "#6c7986")
      (gray-outer-space      "#464646")
      (green-apple           "#4dbf57")
      (green-pistachio       "#91d462")
      (green-sheen           "#75b492")
      (lilac-rich            "#b267e6")
      (orange-royal          "#fd8f3f")
      (purple-medium         "#9686f5")
      (red-lust              "#e21515")
      (red-pastel            "#fc6a5d")
      (red-warm              "#f44747")
      (rose-brilliant        "#fc5fa3")
      (silver-argent         "#c2c0c0")
      (silver-dark           "#e6e6e6")
      (silver-gainsboro      "#dddddd")
      (silver-quick          "#a3a2a2")
      (silver-sonic          "#777777")
      (violet-crayola        "#746db0")
      (white                 "#ffffff")

      (accent                white)
      (bg1                   black-raisin)
      (bg-hl                 gray-outer-space)
      (fg1                   silver-argent)
      (fgd-hl                silver-dark)
      (builtin               purple-medium)
      (comment               gray-metal)
      (constant              purple-medium)
      (doc                   lilac-rich)
      (errorc                red-lust)
      (func                  green-pistachio)
      (keyword               rose-brilliant)
      (line-num-bg           black-olive)
      (line-active-fg        silver-quick)
      (line-inactive-fg      silver-sonic)
      (mode-line-bg-active   black-chinese)
      (mode-line-bg-inactive black-charcoal)
      (mode-line-fg-active   white)
      (mode-line-fg-inactive gray-metal)
      (numeric               purple-medium)
      (string                red-pastel)
      (success               green-sheen)
      (type                  rose-brilliant)
      (variable              blue-jeans)
      (warning               golden-poppy)

      (vc-r                  red-warm)
      (vc-g                  green-apple)
      (vc-b                  blue-queen)

      ;; Will remove these ones at some point.
      (ms-red-bg         "#551b1e")
      (ms-green-bg       "#39422a")
      (ms-blue-bg        "#040e3f")
      (ms-red-bghl       "#74140f")
      (ms-green-bghl     "#4b5332")
      (ms-blue-bghl      "#141e4f"))

  (custom-theme-set-faces
   'ventura-xcode-default
   `(default                                  ((,class (:background ,bg1 :foreground ,fg1))))

   `(font-lock-builtin-face                   ((,class (:foreground ,builtin))))
   `(font-lock-comment-face                   ((,class (:foreground ,comment))))
   `(font-lock-negation-char-face             ((,class (:foreground ,constant))))
   `(font-lock-reference-face                 ((,class (:foreground ,constant))))
   `(font-lock-constant-face                  ((,class (:foreground ,constant))))
   `(font-lock-doc-face                       ((,class (:foreground ,doc))))
   `(font-lock-function-name-face             ((,class (:foreground ,func))))
   `(font-lock-keyword-face                   ((,class (:foreground ,keyword))))
   `(font-lock-string-face                    ((,class (:foreground ,string))))
   `(font-lock-type-face                      ((,class (:foreground ,type))))
   `(font-lock-variable-name-face             ((,class (:foreground ,variable))))
   `(font-lock-warning-face                   ((,class (:foreground ,warning))))
   `(font-lock-regexp-grouping-backslash      ((,class (:foreground ,orange-royal))))
   `(font-lock-regexp-grouping-construct      ((,class (:foreground ,orange-royal))))

   `(region                                   ((,class (:background ,bg-hl :distant-foreground ,fgd-hl :extend nil))))
   `(secondary-selection                      ((,class (:inherit region))))
   `(highlight                                ((,class (:foreground ,blue-dodger :underline t)))) ; link hover
   `(hl-line                                  ((,class (:background ,black-olive))))
   `(fringe                                   ((,class (:background nil :foreground ,white))))
   `(cursor                                   ((,class (:background ,silver-gainsboro))))
   `(show-paren-match-face                    ((,class (:background ,warning))))
   `(show-paren-match                         ((t (:foreground ,gold-satin-sheen :background ,green-apple :bold t))))
   `(show-paren-mismatch                      ((t (:background ,errorc))))
   `(isearch                                  ((,class (:background ,gray-metal))))
   `(vertical-border                          ((,class (:foreground ,black))))
   `(minibuffer-prompt                        ((,class (:foreground ,aqua-pearl :weight normal))))
   `(default-italic                           ((,class (:italic t))))
   `(link                                     ((,class (:foreground ,blue-queen))))
   `(error                                    ((,class (:foreground ,errorc))))
   `(warning                                  ((,class (:foreground ,warning))))
   `(success                                  ((,class (:foreground ,success))))
   `(dired-directory                          ((t (:inherit (font-lock-keyword-face)))))
   `(line-number                              ((,class (:foreground ,line-inactive-fg :background ,line-num-bg))))
   `(line-number-current-line                 ((,class (:foreground ,line-active-fg :background ,line-num-bg))))
   `(header-line                              ((,class (:inherit nil :foreground ,silver-argent :background ,black-pine-tree :box (:line-width -1)))))

   `(mode-line                                ((,class (:foreground ,mode-line-fg-active :background ,mode-line-bg-active))))
   `(mode-line-inactive                       ((,class (:foreground ,mode-line-fg-inactive :background ,mode-line-bg-inactive))))
   `(mode-line-buffer-id                      ((,class (:foreground ,blue-cornflower))))
   `(mode-line-highlight                      ((,class (:foreground ,keyword :box nil :weight normal))))
   `(mode-line-emphasis                       ((,class (:foreground ,fg1))))

   `(company-preview-common                   ((t (:foreground unspecified :background ,black-charcoal))))
   `(company-scrollbar-bg                     ((t (:background ,black-charcoal))))
   `(company-scrollbar-fg                     ((t (:background ,black-raisin))))
   `(company-tooltip                          ((t (:inherit default :background ,black-charcoal))))
   `(company-tooltip-common                   ((t (:foreground ,blue-queen :bold t))))
   `(company-tooltip-selection                ((t (:background ,bg-hl))))
   `(company-tooltip-annotation               ((t (:foreground ,doc)))) ; parameter hints etc.
   `(company-template-field                   ((t (:inherit region))))

   `(org-level-1                              ((,class (:bold nil :foreground ,aqua-pearl
                                                              ,@(when ventura-xcode-default-scale-org-faces (list :height 1.1))))))
   `(org-level-2                              ((,class (:bold nil :foreground ,blue-cornflower))))
   `(org-level-3                              ((,class (:bold nil :foreground ,blue-dodger))))
   `(org-level-4                              ((,class (:bold nil :foreground ,aqua-pearl))))
   `(org-code                                 ((,class (:foreground ,orange-royal))))
   `(org-hide                                 ((,class (:foreground ,white))))
   `(org-date                                 ((,class (:underline t :foreground ,variable) )))
   `(org-footnote                             ((,class (:underline t :foreground ,silver-argent))))
   `(org-link                                 ((,class (:underline t :foreground ,type ))))
   `(org-special-keyword                      ((,class (:foreground ,green-apple))))
   `(org-block                                ((,class (:foreground ,silver-quick :background ,black-chinese :extend t))))
   `(org-quote                                ((,class (:inherit org-block :slant italic))))
   `(org-verse                                ((,class (:inherit org-block :slant italic))))
   `(org-todo                                 ((,class (,@(when ventura-xcode-default-box-org-todo (list :box '(:line-width 1 :color ,red-warm)))
                                                             :foreground ,red-warm :bold nil))))
   `(org-done                                 ((,class (:box (:line-width 1 :color ,green-pistachio) :foreground ,green-pistachio :bold nil ))))
   `(org-warning                              ((,class (:underline t :foreground ,warning))))
   `(org-agenda-structure                     ((,class (:weight normal :foreground ,silver-gainsboro :box (:color ,silver-dark) :background ,black-pine-tree))))
   `(org-agenda-date                          ((,class (:foreground ,variable ,@(when ventura-xcode-default-scale-org-faces (list :height 1.1))))))
   `(org-agenda-date-weekend                  ((,class (:weight normal :foreground ,silver-dark))))
   `(org-agenda-date-today                    ((,class (:weight normal :foreground ,keyword
                                                                ,@(when ventura-xcode-default-scale-org-faces (list :height 1.2))))))
   `(org-agenda-done                          ((,class (:foreground ,black-olive))))
   `(org-scheduled                            ((,class (:foreground ,type))))
   `(org-scheduled-today                      ((,class (:foreground ,func :weight normal
                                                                    ,@(when ventura-xcode-default-scale-org-faces (list :height 1.2))))))
   `(org-ellipsis                             ((,class (:foreground ,builtin))))
   `(org-verbatim                             ((,class (:foreground ,silver-dark))))
   `(org-document-title                       ((,class (:foreground ,type :bold t
                                                                    ,@(when ventura-xcode-default-scale-org-faces (list :height 1.2)))))) ; title
   `(org-document-info                        ((,class (:foreground ,golden-poppy)))) ; author, date etc.
   `(org-document-info-keyword                ((,class (:foreground ,green-apple))))  ; "#+Title", "#+Date" etc.
   `(org-sexp-date                            ((,class (:foreground ,silver-dark))))
   `(org-table                                ((,class (:foreground ,silver-quick :background ,black-pine-tree))))

   `(font-latex-bold-face                     ((,class (:foreground ,type))))
   `(font-latex-italic-face                   ((,class (:foreground ,aqua-pearl :italic t))))
   `(font-latex-string-face                   ((,class (:foreground ,string))))
   `(font-latex-match-reference-keywords      ((,class (:foreground ,constant))))
   `(font-latex-match-variable-keywords       ((,class (:foreground ,variable))))

   `(ido-only-match                           ((,class (:foreground ,keyword))))
   `(ido-subdir                               ((,class (:weight normal :foreground ,black-olive))))
   `(ido-first-match                          ((,class (:foreground ,keyword :bold nil))))

   `(gnus-header-content                      ((,class (:foreground ,keyword))))
   `(gnus-header-from                         ((,class (:foreground ,variable))))
   `(gnus-header-name                         ((,class (:foreground ,type))))
   `(gnus-header-subject                      ((,class (:foreground ,func :bold nil))))

   `(mu4e-view-url-number-face                ((,class (:foreground ,type))))
   `(mu4e-cited-1-face                        ((,class (:foreground ,silver-quick))))
   `(mu4e-cited-7-face                        ((,class (:foreground ,silver-gainsboro))))
   `(mu4e-header-marks-face                   ((,class (:foreground ,type))))

   `(ffap                                     ((,class (:foreground ,silver-dark))))

   `(js2-private-function-call                ((,class (:foreground ,constant))))
   `(js2-jsdoc-html-tag-delimiter             ((,class (:foreground ,string))))
   `(js2-jsdoc-html-tag-name                  ((,class (:foreground ,orange-royal))))
   `(js2-external-variable                    ((,class (:foreground ,type  ))))
   `(js2-function-param                       ((,class (:foreground ,constant))))
   `(js2-jsdoc-value                          ((,class (:foreground ,string))))
   `(js2-private-member                       ((,class (:foreground ,silver-gainsboro))))
   `(js2-warning                              ((t (:underline ,warning))))
   `(js2-error                                ((t (:foreground ,warning :weight normal))))
   `(js2-jsdoc-tag                            ((t (:foreground ,variable))))
   `(js2-jsdoc-type                           ((t (:foreground ,variable))))
   `(js2-instance-member                      ((t (:foreground ,variable))))
   `(js2-object-property                      ((t (:foreground ,func))))
   `(js2-magic-paren                          ((t (:foreground ,constant))))
   `(js2-function-call                        ((t (:foreground ,constant))))
   `(js2-keywords                             ((t (:foreground ,keyword))))
   `(js3-warning-face                         ((,class (:underline ,keyword))))
   `(js3-error-face                           ((,class (:underline ,warning))))
   `(js3-external-variable-face               ((,class (:foreground ,variable))))
   `(js3-function-param-face                  ((,class (:foreground ,aqua-pearl))))
   `(js3-jsdoc-tag-face                       ((,class (:foreground ,keyword))))
   `(js3-instance-member-face                 ((,class (:foreground ,constant))))

   `(ac-completion-face                       ((,class (:underline t :foreground ,keyword))))
   `(info-quoted-name                         ((,class (:foreground ,builtin))))
   `(info-string                              ((,class (:foreground ,string))))
   `(icompletep-determined                    ((,class :foreground ,builtin)))

   `(slime-repl-inputed-output-face           ((,class (:foreground ,type))))
   `(trailing-whitespace                      ((,class :foreground nil :background ,warning)))
   `(lazy-highlight                           ((,class (:background "#613214"))))

   `(undo-tree-visualizer-current-face        ((,class :foreground ,builtin)))
   `(undo-tree-visualizer-default-face        ((,class :foreground ,silver-quick)))
   `(undo-tree-visualizer-unmodified-face     ((,class :foreground ,variable)))
   `(undo-tree-visualizer-register-face       ((,class :foreground ,type)))

   `(rainbow-delimiters-depth-1-face          ((,class :foreground "gold")))
   `(rainbow-delimiters-depth-2-face          ((,class :foreground "orchid")))
   `(rainbow-delimiters-depth-3-face          ((,class :foreground "LightSkyBlue")))
   `(rainbow-delimiters-depth-4-face          ((,class :foreground "gold")))
   `(rainbow-delimiters-depth-5-face          ((,class :foreground "orchid")))
   `(rainbow-delimiters-depth-6-face          ((,class :foreground "LightSkyBlue")))
   `(rainbow-delimiters-depth-7-face          ((,class :foreground "gold")))
   `(rainbow-delimiters-depth-8-face          ((,class :foreground "orchid")))
   `(rainbow-delimiters-depth-9-face          ((,class :foreground "LightSkyBlue")))
   `(rainbow-delimiters-unmatched-face        ((,class :foreground ,errorc)))

   `(magit-item-highlight                     ((,class :background ,black-pine-tree)))
   `(magit-hunk-heading                       ((,class (:background ,black-pine-tree))))
   `(magit-hunk-heading-highlight             ((,class (:background ,black-pine-tree))))
   `(magit-bisect-bad                         ((t (:foreground ,red-lust))))
   `(magit-bisect-good                        ((t (:foreground ,green-apple))))
   `(magit-bisect-skip                        ((t (:foreground ,red-pastel))))
   `(magit-blame-date                         ((t (:foreground ,red-lust))))
   `(magit-blame-heading                      ((t (:foreground ,red-pastel :background ,black-pine-tree :extend t))))
   `(magit-branch                             ((,class (:foreground ,blue-dodger :weight normal))))
   `(magit-branch-current                     ((t (:foreground ,blue-dodger))))
   `(magit-branch-local                       ((t (:foreground ,aqua-pearl))))
   `(magit-branch-remote                      ((t (:foreground ,green-apple))))
   `(magit-cherry-equivalent                  ((t (:foreground ,lilac-rich))))
   `(magit-cherry-unmatched                   ((t (:foreground ,aqua-pearl))))
   `(magit-diff-added                         ((t (:foreground ,silver-quick :background ,ms-green-bg :extend t))))
   `(magit-diff-added-highlight               ((t (:foreground ,silver-gainsboro :background ,ms-green-bghl :extend t))))
   `(magit-diff-removed                       ((t (:foreground ,silver-quick :background ,ms-red-bg :extend t))))
   `(magit-diff-removed-highlight             ((t (:foreground ,silver-gainsboro :background ,ms-red-bghl :extend t))))
   `(magit-diff-base                          ((t (:foreground ,bg1 :background ,red-pastel :extend t))))
   `(magit-diff-base-highlight                ((t (:foreground ,red-pastel :background ,black-pine-tree :extend t))))
   `(magit-diff-context                       ((t (:foreground ,black-olive :extend t))))
   `(magit-diff-context-highlight             ((,class (:foreground ,fg1 :background ,black-charcoal))))
   `(magit-diff-file-header                   ((,class (:foreground ,silver-quick :background ,black-pine-tree))))
   `(magit-diff-file-heading                  ((t (:foreground ,fg1 :extend t))))
   `(magit-diff-file-heading-highlight        ((t (:background ,black-pine-tree :extend t))))
   `(magit-diff-file-heading-selection        ((t (:foreground ,red-pastel :background ,black-pine-tree :extend t))))
   `(magit-diff-hunk-heading                  ((t (:foreground ,fg1 :background ,black-pine-tree :extend t))))
   `(magit-diff-hunk-heading-highlight        ((t (:background ,black-pine-tree :extend t))))
   `(magit-diff-lines-heading                 ((t (:foreground ,golden-poppy :background ,red-lust :extend t))))
   `(magit-diffstat-added                     ((t (:foreground ,green-apple))))
   `(magit-diffstat-removed                   ((t (:foreground ,red-pastel))))
   `(magit-dimmed                             ((t (:foreground ,comment))))
   `(magit-filename                           ((t (:foreground ,lilac-rich))))
   `(magit-hash                               ((t (:foreground ,comment))))
   `(magit-header-line                        ((t (:inherit nil))))
   `(magit-log-author                         ((t (:foreground ,red-pastel))))
   `(magit-log-date                           ((t (:foreground ,blue-dodger))))
   `(magit-log-graph                          ((t (:foreground ,comment))))
   `(magit-mode-line-process                  ((t (:foreground ,red-pastel))))
   `(magit-mode-line-process-error            ((t (:foreground ,red-lust))))
   `(magit-process-ok                         ((t (:inherit success))))
   `(magit-process-ng                         ((t (:inherit error))))
   `(magit-reflog-amend                       ((t (:foreground ,lilac-rich))))
   `(magit-reflog-checkout                    ((t (:foreground ,blue-dodger))))
   `(magit-reflog-cherry-pick                 ((t (:foreground ,green-apple))))
   `(magit-reflog-commit                      ((t (:foreground ,green-apple))))
   `(magit-reflog-merge                       ((t (:foreground ,green-apple))))
   `(magit-reflog-other                       ((t (:foreground ,aqua-pearl))))
   `(magit-reflog-rebase                      ((t (:foreground ,lilac-rich))))
   `(magit-reflog-remote                      ((t (:foreground ,aqua-pearl))))
   `(magit-reflog-reset                       ((t (:inherit error))))
   `(magit-refname                            ((t (:foreground ,comment))))
   `(magit-section-heading                    ((t (:foreground ,lilac-rich))))
   `(magit-section-heading-selection          ((t (:foreground ,red-pastel :extend t))))
   `(magit-section-highlight                  ((t (:background ,black-pine-tree :extend t))))
   `(magit-sequence-drop                      ((t (:foreground ,red-lust))))
   `(magit-sequence-head                      ((t (:foreground ,blue-dodger))))
   `(magit-sequence-part                      ((t (:foreground ,red-pastel))))
   `(magit-sequence-stop                      ((t (:foreground ,green-apple))))
   `(magit-signature-bad                      ((t (:inherit error))))
   `(magit-signature-error                    ((t (:inherit error))))
   `(magit-signature-expired-key              ((t (:foreground ,red-pastel))))
   `(magit-signature-good                     ((t (:inherit success))))
   `(magit-signature-revoked                  ((t (:foreground ,lilac-rich))))
   `(magit-signature-untrusted                ((t (:foreground ,aqua-pearl))))
   `(magit-tag                                ((t (:foreground ,golden-poppy))))

   `(git-commit-summary                       ((t (:inherit default)))) ; magit commit message face

   `(term                                     ((,class (:foreground ,fg1 :background ,bg1))))
   `(term-color-black                         ((,class (:foreground ,black-pine-tree :background ,black-pine-tree))))
   `(term-color-blue                          ((,class (:foreground ,blue-dodger :background ,func))))
   `(term-color-red                           ((,class (:foreground ,red-lust :background ,black-pine-tree))))
   `(term-color-green                         ((,class (:foreground ,green-apple :background ,black-pine-tree))))
   `(term-color-yellow                        ((,class (:foreground ,golden-poppy :background ,variable))))
   `(term-color-magenta                       ((,class (:foreground ,lilac-rich :background ,builtin))))
   `(term-color-cyan                          ((,class (:foreground ,aqua-pearl :background ,string))))
   `(term-color-white                         ((,class (:foreground ,fg1 :background ,silver-quick))))

   `(diredfl-autofile-name                    ((t (:foreground ,black-olive))))
   `(diredfl-compressed-file-name             ((t (:foreground ,golden-poppy))))
   `(diredfl-compressed-file-suffix           ((t (:foreground ,doc))))
   `(diredfl-date-time                        ((t (:foreground ,aqua-pearl))))
   `(diredfl-deletion                         ((t (:foreground ,red-lust :bold t))))
   `(diredfl-deletion-file-name               ((t (:foreground ,red-lust ))))
   `(diredfl-dir-heading                      ((t (:foreground ,blue-dodger :bold t))))
   `(diredfl-dir-name                         ((t (:foreground ,blue-dodger))))
   `(diredfl-dir-priv                         ((t (:foreground ,blue-dodger))))
   `(diredfl-exec-priv                        ((t (:foreground ,green-apple))))
   `(diredfl-executable-tag                   ((t (:foreground ,green-apple))))
   `(diredfl-file-name                        ((t (:foreground ,fg1))))
   `(diredfl-file-suffix                      ((t (:foreground ,doc))))
   `(diredfl-flag-mark                        ((t (:foreground ,golden-poppy :bold t))))
   `(diredfl-ignored-file-name                ((t (:foreground ,doc))))
   `(diredfl-link-priv                        ((t (:foreground ,lilac-rich))))
   `(diredfl-no-priv                          ((t (:foreground ,fg1))))
   `(diredfl-number                           ((t (:foreground ,red-pastel))))
   `(diredfl-other-priv                       ((t (:foreground ,lilac-rich))))
   `(diredfl-rare-priv                        ((t (:foreground ,fg1))))
   `(diredfl-read-priv                        ((t (:foreground ,golden-poppy))))
   `(diredfl-symlink                          ((t (:foreground ,lilac-rich))))
   `(diredfl-tagged-autofile-name             ((t (:foreground ,black-olive))))
   `(diredfl-write-priv                       ((t (:foreground ,red-lust))))

   `(helm-header                              ((,class (:foreground ,silver-quick :background ,bg1 :underline nil :box nil))))
   `(helm-source-header                       ((,class (:foreground ,keyword :background ,bg1 :underline nil :weight normal))))
   `(helm-selection                           ((,class (:background ,bg-hl :underline nil :extend t))))
   `(helm-selection-line                      ((,class (:background ,bg-hl :extend t))))
   `(helm-visible-mark                        ((,class (:foreground ,bg1 :background ,black-pine-tree))))
   `(helm-candidate-number                    ((,class (:foreground ,bg1 :background ,fg1))))
   `(helm-separator                           ((,class (:foreground ,type :background ,bg1))))
   `(helm-time-zone-current                   ((,class (:foreground ,builtin :background ,bg1))))
   `(helm-time-zone-home                      ((,class (:foreground ,type :background ,bg1))))
   `(helm-buffer-not-saved                    ((,class (:foreground ,type :background ,bg1))))
   `(helm-buffer-process                      ((,class (:foreground ,builtin :background ,bg1))))
   `(helm-buffer-saved-out                    ((,class (:foreground ,fg1 :background ,bg1))))
   `(helm-buffer-size                         ((,class (:foreground ,fg1 :background ,bg1))))
   `(helm-ff-directory                        ((,class (:foreground ,func :background ,bg1 :weight normal))))
   `(helm-ff-file                             ((,class (:foreground ,fg1 :background ,bg1 :weight normal))))
   `(helm-ff-executable                       ((,class (:foreground ,orange-royal :background ,bg1 :weight normal))))
   `(helm-ff-invalid-symlink                  ((,class (:foreground ,aqua-pearl :background ,bg1 :weight normal))))
   `(helm-ff-symlink                          ((,class (:foreground ,keyword :background ,bg1 :weight normal))))
   `(helm-ff-prefix                           ((,class (:foreground ,bg1 :background ,keyword :weight normal))))
   `(helm-grep-cmd-line                       ((,class (:foreground ,fg1 :background ,bg1))))
   `(helm-grep-file                           ((,class (:foreground ,fg1 :background ,bg1))))
   `(helm-grep-finish                         ((,class (:foreground ,silver-quick :background ,bg1))))
   `(helm-grep-lineno                         ((,class (:foreground ,fg1 :background ,bg1))))
   `(helm-grep-match                          ((,class (:foreground nil :background nil :inherit helm-match))))
   `(helm-grep-running                        ((,class (:foreground ,func :background ,bg1))))
   `(helm-moccur-buffer                       ((,class (:foreground ,func :background ,bg1))))
   `(helm-source-go-package-godoc-description ((,class (:foreground ,string))))
   `(helm-bookmark-w3m                        ((,class (:foreground ,type))))

   `(web-mode-html-tag-bracket-face           ((,class (:foreground "#808080"))))
   `(web-mode-html-tag-face                   ((,class (:foreground ,keyword))))
   `(web-mode-html-attr-name-face             ((,class (:foreground ,variable))))
   `(web-mode-html-attr-value-face            ((,class (:foreground ,string))))
   `(web-mode-html-attr-equal-face            ((,class (:foreground ,fg1))))
   `(web-mode-builtin-face                    ((,class (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face                    ((,class (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face                   ((,class (:inherit ,font-lock-constant-face))))
   `(web-mode-keyword-face                    ((,class (:foreground ,keyword))))
   `(web-mode-doctype-face                    ((,class (:inherit ,font-lock-doc-face))))
   `(web-mode-function-name-face              ((,class (:inherit ,font-lock-function-name-face))))
   `(web-mode-string-face                     ((,class (:foreground ,string))))
   `(web-mode-type-face                       ((,class (:inherit ,font-lock-type-face))))
   `(web-mode-warning-face                    ((,class (:inherit ,font-lock-warning-face))))
   `(web-mode-json-key-face                   ((,class (:foreground ,string))))
   `(web-mode-json-context-face               ((,class (:foreground ,string))))

   `(diff-header                              ((t (:foreground ,aqua-pearl :background nil))))
   `(diff-file-header                         ((t (:foreground ,silver-gainsboro :background nil))))
   `(diff-hunk-header                         ((t (:foreground ,silver-dark :background ,black-pine-tree))))
   `(diff-added                               ((t (:foreground ,silver-quick :background ,ms-green-bg))))
   `(diff-removed                             ((t (:foreground ,silver-quick :background ,ms-red-bg))))
   `(diff-changed                             ((t (:foreground ,silver-quick :background ,ms-blue-bg))))
   `(diff-refine-added                        ((t (:foreground ,silver-gainsboro :background ,ms-green-bghl))))
   `(diff-refine-removed                      ((t (:foreground ,silver-gainsboro :background ,ms-red-bghl))))
   `(diff-refine-changed                      ((t (:foreground ,silver-gainsboro :background ,ms-blue-bghl))))

   `(ediff-fine-diff-Ancestor                 ((t (:background ,ms-red-bghl))))
   `(ediff-fine-diff-A                        ((t (:background ,ms-red-bghl))))
   `(ediff-fine-diff-B                        ((t (:background ,ms-green-bghl))))
   `(ediff-fine-diff-C                        ((t (:background ,ms-blue-bghl))))
   `(ediff-current-diff-Ancestor              ((t (:background ,ms-red-bg))))
   `(ediff-current-diff-A                     ((t (:background ,ms-red-bg))))
   `(ediff-current-diff-B                     ((t (:background ,ms-green-bg))))
   `(ediff-current-diff-C                     ((t (:background ,ms-blue-bg))))
   `(ediff-even-diff-Ancestor                 ((t (:background ,black-pine-tree))))
   `(ediff-even-diff-A                        ((t (:background ,black-pine-tree))))
   `(ediff-even-diff-B                        ((t (:background ,black-pine-tree))))
   `(ediff-even-diff-C                        ((t (:background ,black-pine-tree))))
   `(ediff-odd-diff-Ancestor                  ((t (:background ,black-pine-tree))))
   `(ediff-odd-diff-A                         ((t (:background ,black-pine-tree))))
   `(ediff-odd-diff-B                         ((t (:background ,black-pine-tree))))
   `(ediff-odd-diff-C                         ((t (:background ,black-pine-tree))))

   `(jde-java-font-lock-package-face          ((t (:foreground ,variable))))
   `(jde-java-font-lock-public-face           ((t (:foreground ,keyword))))
   `(jde-java-font-lock-private-face          ((t (:foreground ,keyword))))
   `(jde-java-font-lock-constant-face         ((t (:foreground ,constant))))
   `(jde-java-font-lock-modifier-face         ((t (:foreground ,aqua-pearl))))
   `(jde-jave-font-lock-protected-face        ((t (:foreground ,keyword))))
   `(jde-java-font-lock-number-face           ((t (:foreground ,numeric))))

   `(centaur-tabs-default                     ((t (:background ,bg1 :foreground ,fg1))))
   `(centaur-tabs-selected                    ((t (:background ,bg1 :foreground ,silver-gainsboro :box nil))))
   `(centaur-tabs-unselected                  ((t (:background ,black-charcoal :foreground ,black-olive :box nil))))
   `(centaur-tabs-selected-modified           ((t (:background ,black-charcoal :foreground ,accent :box nil))))
   `(centaur-tabs-unselected-modified         ((t (:background ,black-charcoal :foreground ,silver-dark :box nil))))
   `(centaur-tabs-active-bar-face             ((t (:background ,accent :box nil))))
   `(centaur-tabs-modified-marker-selected    ((t (:inherit 'centaur-tabs-selected-modified :foreground ,accent :box nil))))
   `(centaur-tabs-modified-marker-unselected  ((t (:inherit 'centaur-tabs-unselected-modified :foreground ,accent :box nil))))

   `(solaire-default-face                     ((t (:inherit default :background ,black-charcoal))))
   `(solaire-minibuffer-face                  ((t (:inherit default :background ,black-charcoal))))
   `(solaire-hl-line-face                     ((t (:inherit hl-line :background ,black-pine-tree))))
   `(solaire-org-hide-face                    ((t (:inherit org-hide :background ,black-charcoal))))

   `(ivy-confirm-face                         ((t (:inherit minibuffer-prompt :foreground ,keyword))))
   `(ivy-current-match                        ((t (:background ,bg-hl :extend t))))
   `(ivy-highlight-face                       ((t (:inherit font-lock-builtin-face))))
   `(ivy-match-required-face                  ((t (:inherit minibuffer-prompt :foreground ,warning))))
   `(ivy-minibuffer-match-face-1              ((t (:inherit isearch))))
   `(ivy-minibuffer-match-face-2              ((t (:inherit ivy-minibuffer-match-face-1))))
   `(ivy-minibuffer-match-face-3              ((t (:inherit ivy-minibuffer-match-face-2))))
   `(ivy-minibuffer-match-face-4              ((t (:inherit ivy-minibuffer-match-face-2))))
   `(ivy-minibuffer-match-highlight           ((t (:inherit ivy-current-match))))
   `(ivy-modified-buffer                      ((t (:inherit default :foreground ,variable))))
   `(ivy-virtual                              ((t (:inherit default :foreground ,doc))))
   `(ivy-posframe                             ((t (:background "#252526"))))

   `(counsel-key-binding                      ((t (:foreground ,variable))))

   `(swiper-match-face-1                      ((t (:inherit ivy-minibuffer-match-face-1))))
   `(swiper-match-face-2                      ((t (:inherit ivy-minibuffer-match-face-2))))
   `(swiper-match-face-3                      ((t (:inherit ivy-minibuffer-match-face-3))))
   `(swiper-match-face-4                      ((t (:inherit ivy-minibuffer-match-face-4))))
   `(swiper-line-face                         ((t (:foreground ,black-olive :background ,black-olive :extend t))))

   `(git-gutter:added                         ((t (:background ,vc-g :foreground ,vc-g :weight normal))))
   `(git-gutter:deleted                       ((t (:background ,vc-r :foreground ,vc-r :weight normal))))
   `(git-gutter:modified                      ((t (:background ,vc-b :foreground ,vc-b :weight normal))))
   `(git-gutter-fr:added                      ((t (:background ,vc-g :foreground ,vc-g :weight normal))))
   `(git-gutter-fr:deleted                    ((t (:background ,vc-r :foreground ,vc-r :weight normal))))
   `(git-gutter-fr:modified                   ((t (:background ,vc-b :foreground ,vc-b :weight normal))))

   `(diff-hl-insert                           ((t (:background ,vc-g :foreground ,vc-g))))
   `(diff-hl-delete                           ((t (:background ,vc-r :foreground ,vc-r))))
   `(diff-hl-change                           ((t (:background ,vc-b :foreground ,vc-b))))

   `(neo-dir-link-face                        ((t (:foreground "#cccccc"))))
   `(neo-header-face                          ((t (:foreground "#cccccc"))))
   `(neo-banner-face                          ((t (:foreground "#cccccc"))))
   `(neo-root-dir-face                        ((t (:foreground "#cccccc"))))
   `(neo-file-link-face                       ((t (:foreground "#aaaaaa"))))
   `(neo-expand-btn-face                      ((t (:foreground "#aaaaaa"))))

   `(sml/global                               ((t (:foreground ,silver-quick :weight normal))))
   `(sml/filename                             ((t (:foreground ,silver-quick :weight normal))))
   `(sml/line-number                          ((t (:foreground ,silver-quick :weight normal))))
   `(sml/prefix                               ((t (:foreground ,silver-quick :weight normal))))
   `(sml/read-only                            ((t (:foreground ,silver-quick :weight normal))))
   `(sml/modes                                ((t (:foreground ,silver-quick :weight normal))))
   `(sml/modified                             ((t (:foreground ,white :weight bold))))
   `(sml/charging                             ((t (:foreground ,green-apple :weight normal))))

   `(evil-ex-substitute-matches               ((t (:foreground ,warning :weight normal :strike-through t))))
   `(evil-ex-substitute-replacement           ((t (:foreground ,aqua-pearl :weight normal))))

   `(hl-todo                                  ((t ,@(when ventura-xcode-default-invert-hl-todo (list :inverse-video t)))))
   `(highlight-numbers-number                 ((t (:foreground ,numeric))))
   `(highlight-operators-face                 ((t (:inherit default))))
   `(highlight-symbol-face                    ((t (:background "#343a40"))))

   `(window-divider                           ((t (:foreground "gray40"))))
   `(window-divider-last-pixel                ((t (:foreground "gray20"))))
   `(window-divider-first-pixel               ((t (:foreground "gray60"))))

   `(tree-sitter-hl-face:method.call          ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:function.call        ((t (:inherit font-lock-function-name-face))))
   `(tree-sitter-hl-face:operator             ((t (:inherit default))))
   `(tree-sitter-hl-face:type.builtin         ((t (:inherit font-lock-keyword-face))))
   `(tree-sitter-hl-face:number               ((t (:inherit highlight-numbers-number))))

   `(tab-bar-tab-inactive                     ((t (:background ,black-charcoal))))
   `(tab-bar-tab                              ((t (:background ,bg1 :foreground ,white))))
   `(tab-bar                                  ((t (:background ,black-charcoal))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'ventura-xcode-default)
(provide 'ventura-xcode-default-theme)

;;; ventura-xcode-default-theme.el ends here

